---
title: "Chapter 1 -- Introduction"
format: html
editor: visual
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
```

## Hi!

Hi! Welcome to the ebook for the second half of IBIO/PLB/ENT 830, the introductory statistics course in Michigan State University's Ecology and Evolutionary Biology Graduate program.

## Learning Goals

Course learning goals go here

## Themes

Throughout the course we'll be talking about the following themes...

## Who I am

I'm an evolutionary geneticist. My lab mostly works on understanding how evolution has shaped quantitative trait variation, especially in the context of environmental variation and genome evolution. We use statistics to infer things about trait variation and genomic sequence variation, and the links between the two.

I'm actually a second-generation statistics teacher -- my dad was a high school math teacher and taught statistics for years. 

## How this book works

Stuff about logistics goes here.

## Acknowledgements

[Yaniv Brandvain](https://cbs.umn.edu/directory/yaniv-brandvain)'s online statistics textbook inspired this project and he has answered so many of my statistical and logistical questions.

This course section was originally developed by [Gideon Bradburd](https://lsa.umich.edu/eeb/people/faculty/gideon-bradburd.html]) and I learned a ton from teaching it.

[Doc Edge](https://edgepopgen.github.io/edgelab/) and his [cool statistics textbook](https://academic.oup.com/book/43993) have been big sources of statistical knowledge.



