project:
  type: book
  output-dir: docs

book:
  title: "EEB 830/831"
  author: "Emily Josephs"
  date: "3/12/2025"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-probability.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
 


