project:
  type: book
  output-dir: docs

book:
  title: "EEB 830 pt 2"
  author: "Emily Josephs"
  date: "3/12/2025"
  search: true
  downloads: [pdf, epub]
  repo-url: https://github.com/emjosephs/msu-eeb830831-quarto
  repo-actions: [edit]
  chapters:
    - index.qmd
    - 01-intro.qmd
    - likelihood.qmd
    - linearModels1.qmd
    - lm-categories.qmd
    - lm-continousvars.qmd
    - pvalues.qmd
    - lm-multiplepredictors.qmd
    - multipletesting.qmd
    - GWAS.qmd
    - part: "Labs"
      chapters:
        - lab1.1-likelihood.qmd
        - lab4.1-ANOVA.qmd
        - lab5.1-regression.qmd



#bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: ["assets/sticky-notes.css"]
 


