project:
  type: book
  output-dir: docs

book:
  title: "EEB 830/831"
  author: "Emily Josephs"
  date: "3/12/2025"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - likelihood.qmd
    - linearModels1.qmd
    - lm-categories.qmd
    - lm-continousvars.qmd
    - pvalues.qmd
    - lm-multiplepredictors.qmd
    - multipletesting.qmd
    - GWAS.qmd
    - part: "Labs"
      chapters:
        - lab3.1-simpleLinearModels.qmd
        - lab4.1-ANOVA.qmd



#bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: ["assets/sticky-notes.css"]
 


